files=def.h getline.c main.c memFunc.c readlines.c writelines.c qsort.c qsortR.c strcmp.c strdircmp.c icstrcmp.c icstrdircmp.c numcmp.c swap.c getField.c storeAlloc.c

sort: $(files)
	gcc -g $(files) -o sort

.PHONY: clean

clean:
	-rm sort
