files=def.h getline.c ic_strCmp.c ic_strdircmp.c main.c memFunc.c numcmp.c qsort.c qsortR.c readlines.c strCmp.c strdircmp.c swap.c writelines.c

sort: $(files)
	gcc -g $(files) -o sort

.PHONY: clean

clean:
	-rm sort
