files=def.h main.c memFunc.c numcmp.c qsort.c qsortR.c readlines.c str_case_cmp.c str_cmp.c strdir_case_cmp.c strdircmp.c swap.c writelines.c getline.c

Sort: $(files)
	gcc -g $(files) -o Sort

.PHONY: clean

clean:
	-rm Sort
